package com.qurve.badge.domain;

public enum BadgeConditionType {
    FIRST_LOGIN,
    ATTENDANCE_STREAK,
    PROBLEM_SUBMISSION_COUNT,
    CORRECT_PROBLEM_COUNT,
    ACCURACY_RATE,
    PERFECT_SET,
    CONSECUTIVE_PERFECT_SET,
    WRONG_NOTE_STUDY_COUNT,
    WRONG_RETRY_CORRECT_COUNT,
    WORD_STUDY_COUNT,
    WORD_BOOKMARK_COUNT,
    CHALLENGE_CREATED_COUNT,
    CHALLENGE_COMPLETED_COUNT,
    TOTAL_STUDY_TIME,
    LEVEL_UP_COUNT,
    LEVEL_MASTER,
    ALL_LEVEL_MASTER,
    AI_COACH_USAGE_COUNT
}
